refs #17 ショートコードを追加する

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -36,6 +36,12 @@ jobs:
     needs: generate-images
     env:
       HUGO_VERSION: 0.114.0
+      ARTIFACT: artifact
+      VOICEVOX_PATH: content/voicevox
+      YOUR_PAT: ${{ secrets.ANCIENT_BLOG_PAT}}
+      YOUR_OWNER: ancient-blog
+      YOUR_REPO: hugo.github.io
+      YOUR_ARTIFACT_NAME: voicevox-data
     steps:
       - name: Install Hugo CLI
         run: |
@@ -47,6 +53,39 @@ jobs:
         uses: actions/checkout@v3
         with:
           submodules: recursive
+      - name: Install jq
+        run: |
+          sudo apt-get update
+          sudo apt-get install jq -y
+      - name: Get Artifacts using the GitHub API
+        run: |
+          curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${YOUR_PAT}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            https://api.github.com/repos/${YOUR_OWNER}/${YOUR_REPO}/actions/artifacts > artifacts.json
+
+          # GitHub APIからarchive_download_urlを取得し、日付でソートして最新のアーティファクトを取得
+          archive_download_url=$(cat artifacts.json | jq -r '.artifacts | sort_by(.created_at) | reverse | .[0].archive_download_url')
+          if [ -z "$archive_download_url" ]; then
+            echo "No matching artifacts found for ${YOUR_ARTIFACT_NAME}"
+            exit 1
+          fi
+          curl -L \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${YOUR_PAT}" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            ${archive_download_url} \ 
+            -o artifacts.zip
+          ls -lh
+        continue-on-error: true  # 初回で成果物がない場合エラーを許可します
+      - name: Unzip Artifact
+        run: |
+          if [ -f artifacts.zip ]; then
+            unzip artifacts.zip -d ${VOICEVOX_PATH}
+          else
+            echo "artifacts.zip not found, skipping unzip."
+          fi
       - name: To set up Google Analytics tracking code in a Hugo website's config.toml file.
         run: |
           sed -i s/G-XXXXXXXXXX/${{ vars.GOOGLE_ANALYTICS_TRACKING_CODE }}/ config.toml
